/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
package com.jnr15.vistas;
import com.jnr15.ConstantesComunes;
import com.jnr15.ControladorBase;
import com.jnr15.ControladorWSBaleares;
import com.jnr15.ControladorWSJCCM;
import com.jnr15.asturias.ws.ActualizarDatosEquidos;
import com.jnr15.keystore.KeyStore;
import com.jnr15.logs.Log;
import configBBDD.Propiedades;
import dao.IDAODatosEquidosComAut;
import dao.JDBCDAODatosEquidosComAut;
import jakarta.xml.bind.JAXBContext;
import jakarta.xml.bind.Marshaller;
import java.awt.Desktop;
import java.io.File;
import java.io.FileWriter;
import java.io.StringWriter;
import java.net.URI;
import javax.swing.JOptionPane;
import modelo.DatosEquidosComAut;

/**
 *
 * @author jesus
 */
public class MenuWSComAut extends javax.swing.JFrame {
    
    private static int TIPO_ACCESO = 2;
    private static int PRUEBA_MASIVA = 0;

    /**
     * Creates new form MenuWSComAut
     */
    public MenuWSComAut() {
        initKeyStore();
        ajustSizeHandshakeMessage();
        initComponents();
    }
    
    private static void initKeyStore(){
        KeyStore.cargarKeyStore();
        Propiedades.obtenerPropiedades().modificarPropiedadesConexionBBDD(getMaquina(), getPuerto(), "uegha", "jesus", "19811224");
    }
    
    private static void ajustSizeHandshakeMessage(){
        //Ajustamos el tamaño a dos veces lo establecido por defecto (32768), siendo el resultado de 65536
        System.setProperty("jdk.tls.maxHandshakeMessageSize", "65536");
    }
    
    private static String getMaquina(){
        if(TIPO_ACCESO==0)
            return "127.0.0.1";
        if(TIPO_ACCESO==1)
            return "192.168.1.35";
        return "invengenio.com";
    }
    
    private static String getPuerto(){
        if(TIPO_ACCESO==0 || TIPO_ACCESO==1)
            return "3306";
        return "2224";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        menuBar = new javax.swing.JMenuBar();
        menuEjecutarSolicitudesPendientes = new javax.swing.JMenu();
        ejecutarSolicitudesPendientes = new javax.swing.JMenuItem();
        menuAndalucia = new javax.swing.JMenu();
        envioPorUelnAndalucia = new javax.swing.JMenuItem();
        menuObtenerDatosBasicosAndalucia = new javax.swing.JMenuItem();
        menuCastillaYLeon = new javax.swing.JMenu();
        envioPorUelnCastillaYLeon = new javax.swing.JMenuItem();
        menuObtenerDatosBasicosCastillaYLeon = new javax.swing.JMenuItem();
        menuExtremadura = new javax.swing.JMenu();
        envioPorUelnExtremadura = new javax.swing.JMenuItem();
        menuNavarra = new javax.swing.JMenu();
        abrirAplicacionWebNavarra = new javax.swing.JMenuItem();
        menuAsturias = new javax.swing.JMenu();
        generarXMLAsturias = new javax.swing.JMenuItem();
        menuCastillaLaMancha = new javax.swing.JMenu();
        menuRegistrarEjemplarCastillaMancha = new javax.swing.JMenuItem();
        menuConsultarEstadoSolicitudCastillaMancha = new javax.swing.JMenuItem();
        menuConsultarDatosEjemplarCastillaMancha = new javax.swing.JMenuItem();
        menuMadrid = new javax.swing.JMenu();
        envioPorUelnMadrid = new javax.swing.JMenuItem();
        menuObtenerDatosBasicosMadrid = new javax.swing.JMenuItem();
        menuGalicia = new javax.swing.JMenu();
        menuRegistrarEjemplarGalicia = new javax.swing.JMenuItem();
        menuBaleares = new javax.swing.JMenu();
        altaEquidoBaleares = new javax.swing.JMenuItem();
        menuActualizarEquidoBaleares = new javax.swing.JMenuItem();
        consultaEquidoBaleares = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        abrirAplicacionWebNavarra1 = new javax.swing.JMenuItem();
        menuMAPA = new javax.swing.JMenu();
        menuConsultarComunidadAutonomaCompetente = new javax.swing.JMenuItem();
        menuConsultarComunidadOrganismoEmisor = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WSComAut - by ./Invengenio (Jesús Nieto Rodríguez) - jesusnieto@invengenio.com");

        menuEjecutarSolicitudesPendientes.setText("Ejecutar Solicitudes Pendientes |");

        ejecutarSolicitudesPendientes.setText("Ejecutar");
        ejecutarSolicitudesPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejecutarSolicitudesPendientesActionPerformed(evt);
            }
        });
        menuEjecutarSolicitudesPendientes.add(ejecutarSolicitudesPendientes);

        menuBar.add(menuEjecutarSolicitudesPendientes);

        menuAndalucia.setText("Andalucía |");

        envioPorUelnAndalucia.setMnemonic('x');
        envioPorUelnAndalucia.setText("Envío por UELN");
        envioPorUelnAndalucia.setToolTipText("");
        envioPorUelnAndalucia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envioPorUelnAndaluciaActionPerformed(evt);
            }
        });
        menuAndalucia.add(envioPorUelnAndalucia);

        menuObtenerDatosBasicosAndalucia.setText("Otener datos equido por ueln");
        menuObtenerDatosBasicosAndalucia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuObtenerDatosBasicosAndaluciaActionPerformed(evt);
            }
        });
        menuAndalucia.add(menuObtenerDatosBasicosAndalucia);

        menuBar.add(menuAndalucia);
        menuAndalucia.getAccessibleContext().setAccessibleName("andalucia");

        menuCastillaYLeon.setText("Castilla y León |");

        envioPorUelnCastillaYLeon.setText("Envio por UELN");
        envioPorUelnCastillaYLeon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envioPorUelnCastillaYLeonActionPerformed(evt);
            }
        });
        menuCastillaYLeon.add(envioPorUelnCastillaYLeon);

        menuObtenerDatosBasicosCastillaYLeon.setText("Otener datos equido por ueln");
        menuObtenerDatosBasicosCastillaYLeon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuObtenerDatosBasicosCastillaYLeonActionPerformed(evt);
            }
        });
        menuCastillaYLeon.add(menuObtenerDatosBasicosCastillaYLeon);

        menuBar.add(menuCastillaYLeon);
        menuCastillaYLeon.getAccessibleContext().setAccessibleName("castillaYLeon");

        menuExtremadura.setText("Extremadura |");

        envioPorUelnExtremadura.setText("Envío por UELN");
        envioPorUelnExtremadura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envioPorUelnExtremaduraActionPerformed(evt);
            }
        });
        menuExtremadura.add(envioPorUelnExtremadura);

        menuBar.add(menuExtremadura);

        menuNavarra.setText("Navarra |");

        abrirAplicacionWebNavarra.setText("Abrir Aplicación Web");
        abrirAplicacionWebNavarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirAplicacionWebNavarraActionPerformed(evt);
            }
        });
        menuNavarra.add(abrirAplicacionWebNavarra);

        menuBar.add(menuNavarra);

        menuAsturias.setText("Asturias |");

        generarXMLAsturias.setText("Generar XML");
        generarXMLAsturias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarXMLAsturiasActionPerformed(evt);
            }
        });
        menuAsturias.add(generarXMLAsturias);

        menuBar.add(menuAsturias);

        menuCastillaLaMancha.setText("Castilla La Mancha |");

        menuRegistrarEjemplarCastillaMancha.setText("Registrar Ejemplar");
        menuRegistrarEjemplarCastillaMancha.setActionCommand("registrarEjemplar");
        menuRegistrarEjemplarCastillaMancha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarEjemplarCastillaManchaActionPerformed(evt);
            }
        });
        menuCastillaLaMancha.add(menuRegistrarEjemplarCastillaMancha);

        menuConsultarEstadoSolicitudCastillaMancha.setText("Consultar Estado Solicitud");
        menuConsultarEstadoSolicitudCastillaMancha.setActionCommand("consultarEstadoSolicitud");
        menuConsultarEstadoSolicitudCastillaMancha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarEstadoSolicitudCastillaManchaActionPerformed(evt);
            }
        });
        menuCastillaLaMancha.add(menuConsultarEstadoSolicitudCastillaMancha);

        menuConsultarDatosEjemplarCastillaMancha.setText("Consultar Datos Ejemplar");
        menuConsultarDatosEjemplarCastillaMancha.setActionCommand("consultarDatosEjemplar");
        menuConsultarDatosEjemplarCastillaMancha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarDatosEjemplarCastillaManchaActionPerformed(evt);
            }
        });
        menuCastillaLaMancha.add(menuConsultarDatosEjemplarCastillaMancha);

        menuBar.add(menuCastillaLaMancha);

        menuMadrid.setText("Madrid |");

        envioPorUelnMadrid.setText("Envio por UELN");
        envioPorUelnMadrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envioPorUelnMadridActionPerformed(evt);
            }
        });
        menuMadrid.add(envioPorUelnMadrid);

        menuObtenerDatosBasicosMadrid.setText("Obtener datos equido por UELN");
        menuObtenerDatosBasicosMadrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuObtenerDatosBasicosMadridActionPerformed(evt);
            }
        });
        menuMadrid.add(menuObtenerDatosBasicosMadrid);

        menuBar.add(menuMadrid);

        menuGalicia.setText("Galicia |");

        menuRegistrarEjemplarGalicia.setText("Registrar Ejemplar");
        menuRegistrarEjemplarGalicia.setActionCommand("registrarEjemplar");
        menuRegistrarEjemplarGalicia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarEjemplarGaliciaActionPerformed(evt);
            }
        });
        menuGalicia.add(menuRegistrarEjemplarGalicia);

        menuBar.add(menuGalicia);

        menuBaleares.setText("Baleares |");
        menuBaleares.setToolTipText("");

        altaEquidoBaleares.setText("Alta Equido");
        altaEquidoBaleares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaEquidoBalearesActionPerformed(evt);
            }
        });
        menuBaleares.add(altaEquidoBaleares);

        menuActualizarEquidoBaleares.setText("Actualizar Equido");
        menuActualizarEquidoBaleares.setActionCommand("actualizarEquidoBaleares");
        menuActualizarEquidoBaleares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActualizarEquidoBalearesActionPerformed(evt);
            }
        });
        menuBaleares.add(menuActualizarEquidoBaleares);

        consultaEquidoBaleares.setText("Consultar Equido");
        consultaEquidoBaleares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaEquidoBalearesActionPerformed(evt);
            }
        });
        menuBaleares.add(consultaEquidoBaleares);

        menuBar.add(menuBaleares);

        jMenu7.setText("Cantabria |");

        abrirAplicacionWebNavarra1.setText("Abrir Aplicación Web");
        abrirAplicacionWebNavarra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirAplicacionWebCantabria(evt);
            }
        });
        jMenu7.add(abrirAplicacionWebNavarra1);

        menuBar.add(jMenu7);

        menuMAPA.setText("MAPA");

        menuConsultarComunidadAutonomaCompetente.setText("Consultar CCAA competente por UELN");
        menuConsultarComunidadAutonomaCompetente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarComunidadAutonomaCompetenteActionPerformed(evt);
            }
        });
        menuMAPA.add(menuConsultarComunidadAutonomaCompetente);

        menuConsultarComunidadOrganismoEmisor.setText("Consultar CCAA Organismo Emisor");
        menuConsultarComunidadOrganismoEmisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarComunidadOrganismoEmisorActionPerformed(evt);
            }
        });
        menuMAPA.add(menuConsultarComunidadOrganismoEmisor);

        menuBar.add(menuMAPA);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1216, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void envioPorUelnAndaluciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envioPorUelnAndaluciaActionPerformed
        ViewEnvioPorUELN vista = new ViewEnvioPorUELN(ConstantesComunes.CODIGO_UBICACION_ANDALUCIA.getString());
        this.getContentPane().add(vista);
        vista.setVisible(true);
    }//GEN-LAST:event_envioPorUelnAndaluciaActionPerformed

    private void envioPorUelnCastillaYLeonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envioPorUelnCastillaYLeonActionPerformed
        ViewEnvioPorUELN vista = new ViewEnvioPorUELN(ConstantesComunes.CODIGO_UBICACION_CASTILLAYLEON.getString());
        this.getContentPane().add(vista);
        vista.setVisible(true);
    }//GEN-LAST:event_envioPorUelnCastillaYLeonActionPerformed

    private void ejecutarSolicitudesPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejecutarSolicitudesPendientesActionPerformed
        try {
            ControladorBase.obtenerControlador().ejecutarSolicitudesMasivamente();
        } catch (Exception e) {
            MostrarMensajes.mensajeExcepcion(e);
        }
    }//GEN-LAST:event_ejecutarSolicitudesPendientesActionPerformed
  
    private void menuObtenerDatosBasicosAndaluciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuObtenerDatosBasicosAndaluciaActionPerformed
        ViewDatosBasicosEquinoPorUELN vista = new ViewDatosBasicosEquinoPorUELN(ConstantesComunes.CODIGO_UBICACION_ANDALUCIA.getString());
        this.getContentPane().add(vista);
        vista.setVisible(true);
    }//GEN-LAST:event_menuObtenerDatosBasicosAndaluciaActionPerformed

    private void menuObtenerDatosBasicosCastillaYLeonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuObtenerDatosBasicosCastillaYLeonActionPerformed
        ViewDatosBasicosEquinoPorUELN vista = new ViewDatosBasicosEquinoPorUELN(ConstantesComunes.CODIGO_UBICACION_CASTILLAYLEON.getString());
        this.getContentPane().add(vista);
        vista.setVisible(true);
    }//GEN-LAST:event_menuObtenerDatosBasicosCastillaYLeonActionPerformed

    private void menuConsultarComunidadAutonomaCompetenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarComunidadAutonomaCompetenteActionPerformed
        try {
            String ueln = JOptionPane.showInputDialog(new String("Por favor, introduce el UELN a consultar"));
            if(ueln!=null && (ueln=ueln.trim()).length()>0){
                String[] res = ControladorBase.obtenerControlador().getComunidadCompetenteSegunMinisterio(ueln);
                String mensaje = "No existen datos para el UELN indicado";
                if(res!=null && res.length==2)
                    mensaje = "La CCAA competente es: " + res[0] + " " + res[1];
                MostrarMensajes.mensajeInformativo(mensaje);
            }
        } catch (Exception e) {
            MostrarMensajes.mensajeExcepcion(e);
        }
        
    }//GEN-LAST:event_menuConsultarComunidadAutonomaCompetenteActionPerformed

    private void menuConsultarComunidadOrganismoEmisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarComunidadOrganismoEmisorActionPerformed
        // TODO add your handling code here:
        try {
            String ueln = JOptionPane.showInputDialog(new String("Por favor, introduce el UELN a consultar"));
            if(ueln!=null && (ueln=ueln.trim()).length()>0){
                String[] res = ControladorBase.obtenerControlador().getComunidadOrganismoEmisor(ueln);
                String mensaje = "No existen datos para el UELN indicado";
                if(res!=null && res.length==2)
                    mensaje = "El organismo emisor es: " + res[0] + " " + res[1];
                MostrarMensajes.mensajeInformativo(mensaje);
            }
        } catch (Exception e) {
            MostrarMensajes.mensajeExcepcion(e);
        }
    }//GEN-LAST:event_menuConsultarComunidadOrganismoEmisorActionPerformed

    private void envioPorUelnExtremaduraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envioPorUelnExtremaduraActionPerformed
        ViewEnvioPorUELN vista = new ViewEnvioPorUELN(ConstantesComunes.CODIGO_UBICACION_EXTREMADURA.getString());
        this.getContentPane().add(vista);
        vista.setVisible(true);
    }//GEN-LAST:event_envioPorUelnExtremaduraActionPerformed

    private void abrirAplicacionWebNavarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirAplicacionWebNavarraActionPerformed
        try {
            Desktop.getDesktop().browse(URI.create("https://administracionelectronica.navarra.es/GEGAN5"));
        } catch (Exception e) {
            MostrarMensajes.mensajeExcepcion(e);
        }
    }//GEN-LAST:event_abrirAplicacionWebNavarraActionPerformed

    private void generarXMLAsturiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarXMLAsturiasActionPerformed
        // TODO add your handling code here:
        //Solicitamos el UELN del ejemplar para el cual generar el fichero XML
        String ueln = MostrarMensajes.mensajeSolicitudUELN();
        if(ueln==null || ueln.trim().length()==0)
            return;
        try {
            IDAODatosEquidosComAut daoDatosEquidosJA = JDBCDAODatosEquidosComAut.obtenerDao();
            DatosEquidosComAut datosEquido = daoDatosEquidosJA.datosEquidosComAutPorUELN(ueln);
            if(datosEquido==null){
                MostrarMensajes.mensajeInformativo("No hay datos para el UELN indicado");
                return;
            }
            ActualizarDatosEquidos actualizar = new ActualizarDatosEquidos();
            actualizar.addAnimal(datosEquido);
            JAXBContext contexto = JAXBContext.newInstance(ActualizarDatosEquidos.class);
            Marshaller marshaller = contexto.createMarshaller();
            marshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, Boolean.TRUE);
            marshaller.setProperty(Marshaller.JAXB_FRAGMENT,Boolean.TRUE);//Para eliminar la declaración <?xml version="1.0" ....> inicial
            StringWriter sw = new StringWriter();
            sw.write("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
            marshaller.marshal(actualizar, sw);
            File fichero = MostrarMensajes.rutaFichero(ueln+".xml");
            if(fichero!=null){
                FileWriter fw = new FileWriter(fichero);
                fw.write(sw.toString());
                fw.flush();
                fw.close();
                MostrarMensajes.mensajeInformativo("Fichero generado con éxito");
            }  
        } catch (Exception e) {
            MostrarMensajes.mensajeExcepcion(e);
        }
    }//GEN-LAST:event_generarXMLAsturiasActionPerformed

    private void menuConsultarEstadoSolicitudCastillaManchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarEstadoSolicitudCastillaManchaActionPerformed
        // TODO add your handling code here:
        try {
            String idSolicitud = JOptionPane.showInputDialog(new String("Por favor, introduce el código de solicitud: "));
            if(idSolicitud!=null && (idSolicitud=idSolicitud.trim()).length()>0){
                String res = ControladorWSJCCM.obtenerControlador().consultarEstadoSolicitud(idSolicitud);
                String mensaje = "No existen datos para el código de solicitud indicado";
                if(res!=null && res.length()>0)
                    mensaje = res;
                MostrarMensajes.mensajeInformativo(mensaje);
            }
        } catch (Exception e) {
            MostrarMensajes.mensajeExcepcion(e);
        }
    }//GEN-LAST:event_menuConsultarEstadoSolicitudCastillaManchaActionPerformed

    private void menuRegistrarEjemplarCastillaManchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarEjemplarCastillaManchaActionPerformed
        // TODO add your handling code here:
        ViewEnvioPorUELN vista = new ViewEnvioPorUELN(ConstantesComunes.CODIGO_UBICACION_CASTILLA_LA_MANCHA.getString());
        this.getContentPane().add(vista);
        vista.setVisible(true);
    }//GEN-LAST:event_menuRegistrarEjemplarCastillaManchaActionPerformed

    private void menuConsultarDatosEjemplarCastillaManchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarDatosEjemplarCastillaManchaActionPerformed
        // TODO add your handling code here:
        try {
            String ueln = JOptionPane.showInputDialog(new String("Por favor, introduce el ueln: "));
            if(ueln!=null && (ueln=ueln.trim()).length()>0){
                String res = ControladorWSJCCM.obtenerControlador().consultarDatosAnimal(ueln);
                String mensaje = "No existen datos para el ueln indicado";
                if(res!=null && res.length()>0)
                    mensaje = res;
                MostrarMensajes.mensajeInformativo(mensaje);
            }
        } catch (Exception e) {
            MostrarMensajes.mensajeExcepcion(e);
        }
    }//GEN-LAST:event_menuConsultarDatosEjemplarCastillaManchaActionPerformed

    private void envioPorUelnMadridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envioPorUelnMadridActionPerformed
        // TODO add your handling code here:
        ViewEnvioPorUELN vista = new ViewEnvioPorUELN(ConstantesComunes.CODIGO_UBICACION_MADRID.getString());
        this.getContentPane().add(vista);
        vista.setVisible(true);
    }//GEN-LAST:event_envioPorUelnMadridActionPerformed

    private void menuObtenerDatosBasicosMadridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuObtenerDatosBasicosMadridActionPerformed
        // TODO add your handling code here:
        ViewDatosBasicosEquinoPorUELN vista = new ViewDatosBasicosEquinoPorUELN(ConstantesComunes.CODIGO_UBICACION_MADRID.getString());
        this.getContentPane().add(vista);
        vista.setVisible(true);
    }//GEN-LAST:event_menuObtenerDatosBasicosMadridActionPerformed

    private void menuRegistrarEjemplarGaliciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarEjemplarGaliciaActionPerformed
        // TODO add your handling code here:
        ViewEnvioPorUELN vista = new ViewEnvioPorUELN(ConstantesComunes.CODIGO_UBICACION_GALICIA.getString());
        this.getContentPane().add(vista);
        vista.setVisible(true);
    }//GEN-LAST:event_menuRegistrarEjemplarGaliciaActionPerformed

    private void altaEquidoBalearesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaEquidoBalearesActionPerformed
        // TODO add your handling code here:
        ViewEnvioPorUELN vista = new ViewEnvioPorUELN(ConstantesComunes.CODIGO_UBICACION_BALEARES.getString());
        this.getContentPane().add(vista);
        vista.setVisible(true);
    }//GEN-LAST:event_altaEquidoBalearesActionPerformed

    private void consultaEquidoBalearesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaEquidoBalearesActionPerformed
        // TODO add your handling code here:
        try {
            String ueln = JOptionPane.showInputDialog(new String("Por favor, introduce el ueln: "));
            if(ueln!=null && (ueln=ueln.trim()).length()>0){
                String res = ControladorWSBaleares.obtenerControlador().consultaEquido(ueln);
                String mensaje = "No existen datos para el ueln indicado";
                if(res!=null && res.length()>0)
                    mensaje = res;
                MostrarMensajes.mensajeInformativo(mensaje);
            }
        } catch (Exception e) {
            MostrarMensajes.mensajeExcepcion(e);
        }
    }//GEN-LAST:event_consultaEquidoBalearesActionPerformed

    private void menuActualizarEquidoBalearesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActualizarEquidoBalearesActionPerformed
        // TODO add your handling code here:
        ViewEnvioPorUELN vista = new ViewEnvioPorUELN(ConstantesComunes.TITULO_VENTANA_BALEARES_ACTUALIZAR_EQUIDO.getString());
        this.getContentPane().add(vista);
        vista.setVisible(true);
    }//GEN-LAST:event_menuActualizarEquidoBalearesActionPerformed

    private void abrirAplicacionWebCantabria(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirAplicacionWebCantabria
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(URI.create("https://intercambio.cantabria.es/index.php/s/yiOhTixOQHcWTlW"));
        } catch (Exception e) {
            MostrarMensajes.mensajeExcepcion(e);
        }
    }//GEN-LAST:event_abrirAplicacionWebCantabria

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuWSComAut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuWSComAut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuWSComAut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuWSComAut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        if(PRUEBA_MASIVA==1){
            TIPO_ACCESO = 1;
            try {
                initKeyStore();
                ajustSizeHandshakeMessage();
                ControladorBase.obtenerControlador().ejecutarSolicitudesMasivamente();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        else if (args.length == 0) {
            java.awt.EventQueue.invokeLater(() -> {
                new MenuWSComAut().setVisible(true);
            });
        }
        else{
            try {
                TIPO_ACCESO = Integer.parseInt(args[0]);
                initKeyStore();
                ajustSizeHandshakeMessage();
                String argumento2 = args[1];
                if(argumento2!=null && argumento2.equals("0")){
                    java.awt.EventQueue.invokeLater(() -> {
                        new MenuWSComAut().setVisible(true);
                    });
                }
                else
                    ControladorBase.obtenerControlador().ejecutarSolicitudesMasivamente();
            } catch (Exception e) {
                try {
                    Log.registrarExcepcion(e);
                } catch (Exception e2) {
                    e2.printStackTrace();
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrirAplicacionWebNavarra;
    private javax.swing.JMenuItem abrirAplicacionWebNavarra1;
    private javax.swing.JMenuItem altaEquidoBaleares;
    private javax.swing.JMenuItem consultaEquidoBaleares;
    private javax.swing.JMenuItem ejecutarSolicitudesPendientes;
    private javax.swing.JMenuItem envioPorUelnAndalucia;
    private javax.swing.JMenuItem envioPorUelnCastillaYLeon;
    private javax.swing.JMenuItem envioPorUelnExtremadura;
    private javax.swing.JMenuItem envioPorUelnMadrid;
    private javax.swing.JMenuItem generarXMLAsturias;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem menuActualizarEquidoBaleares;
    private javax.swing.JMenu menuAndalucia;
    private javax.swing.JMenu menuAsturias;
    private javax.swing.JMenu menuBaleares;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCastillaLaMancha;
    private javax.swing.JMenu menuCastillaYLeon;
    private javax.swing.JMenuItem menuConsultarComunidadAutonomaCompetente;
    private javax.swing.JMenuItem menuConsultarComunidadOrganismoEmisor;
    private javax.swing.JMenuItem menuConsultarDatosEjemplarCastillaMancha;
    private javax.swing.JMenuItem menuConsultarEstadoSolicitudCastillaMancha;
    private javax.swing.JMenu menuEjecutarSolicitudesPendientes;
    private javax.swing.JMenu menuExtremadura;
    private javax.swing.JMenu menuGalicia;
    private javax.swing.JMenu menuMAPA;
    private javax.swing.JMenu menuMadrid;
    private javax.swing.JMenu menuNavarra;
    private javax.swing.JMenuItem menuObtenerDatosBasicosAndalucia;
    private javax.swing.JMenuItem menuObtenerDatosBasicosCastillaYLeon;
    private javax.swing.JMenuItem menuObtenerDatosBasicosMadrid;
    private javax.swing.JMenuItem menuRegistrarEjemplarCastillaMancha;
    private javax.swing.JMenuItem menuRegistrarEjemplarGalicia;
    // End of variables declaration//GEN-END:variables

}
