/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.jnr15.vistas;

import com.jnr15.ConstantesComunes;
import com.jnr15.ControladorBase;
import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jesus
 */
public class ViewDatosBasicosEquinoPorUELN extends javax.swing.JInternalFrame {
    
    private final String codigoComunidadAutonoma;

    /**
     * Creates new form ViewDatosBasicosEquinoPorUELN
     */
    public ViewDatosBasicosEquinoPorUELN(String codigoComunidadAutonoma) {
        initComponents();
        this.codigoComunidadAutonoma = codigoComunidadAutonoma;
        if(this.codigoComunidadAutonoma.equals(ConstantesComunes.CODIGO_UBICACION_ANDALUCIA.getString()))
            this.setTitle("DATOS BÁSICOS EQUINO POR UELN - ANDALUCÍA");
        else if(this.codigoComunidadAutonoma.equals(ConstantesComunes.CODIGO_UBICACION_CASTILLAYLEON.getString()))
            this.setTitle("DATOS BÁSICOS EQUINO POR UELN - CASTILLA Y LEÓN");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lUELN = new javax.swing.JLabel();
        cUELN = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tDatos = new javax.swing.JTable();
        bLimpiar = new javax.swing.JButton();

        setClosable(true);

        lUELN.setText("UELN:");
        lUELN.setName("lUELN"); // NOI18N

        cUELN.setBackground(new java.awt.Color(255, 255, 153));
        cUELN.setName("cUELN"); // NOI18N
        cUELN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cUELNKeyPressed(evt);
            }
        });

        tDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Campo", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tDatos.setName("tDatos"); // NOI18N
        jScrollPane1.setViewportView(tDatos);

        bLimpiar.setText("Limpiar");
        bLimpiar.setName("bLimpiar"); // NOI18N
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(lUELN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cUELN, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(bLimpiar)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lUELN)
                    .addComponent(cUELN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(bLimpiar)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cUELNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cUELNKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            int numeroFilas = ((DefaultTableModel)tDatos.getModel()).getRowCount();
            if(numeroFilas>0){
                MostrarMensajes.mensajeInformativo("Por favor, pulse \"Limpiar\" antes de realizar una nueva consulta.");
                return;
            }
            try {
                DefaultTableModel model = ControladorBase.obtenerControlador().modeloTablaObtenerDatosEquidosDesdeCCAA(codigoComunidadAutonoma, cUELN.getText().trim(), tDatos);
                if(model==null || model.getRowCount()==0){
                    MostrarMensajes.mensajeInformativo("Sin datos para el UELN indicado");
                }
            } catch (Exception e) {
                MostrarMensajes.mensajeExcepcion(e);
            }
        }
    }//GEN-LAST:event_cUELNKeyPressed

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed
        tDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Campo", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        cUELN.setText("");
    }//GEN-LAST:event_bLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLimpiar;
    private javax.swing.JTextField cUELN;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lUELN;
    private javax.swing.JTable tDatos;
    // End of variables declaration//GEN-END:variables
}
