/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.jnr15.vistas;

import com.jnr15.ConstantesComunes;
import com.jnr15.ControladorBase;
import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jesus
 */
public class ViewEnvioPorUELN extends javax.swing.JInternalFrame {
    
    private final String codigoComunidadAutonoma;

    /**
     * Creates new form ViewAndaluciaEnvioPorUELN
     * @param codigoComunidadAutonoma
     */
    public ViewEnvioPorUELN(String codigoComunidadAutonoma) {
        initComponents();
        this.codigoComunidadAutonoma = codigoComunidadAutonoma;
        if(this.codigoComunidadAutonoma.equals(ConstantesComunes.CODIGO_UBICACION_CASTILLAYLEON.getString())){
            checkCambioTitularidad.setEnabled(true);
            checkModificarEquido.setEnabled(false);
            bBorrarProducto.setEnabled(true);
        }
        else if(this.codigoComunidadAutonoma.equals(ConstantesComunes.CODIGO_UBICACION_EXTREMADURA.getString())){
            checkCambioTitularidad.setEnabled(true);
            checkModificarEquido.setEnabled(true);
            bBorrarProducto.setEnabled(false);
        }
        else {
            checkCambioTitularidad.setEnabled(false);
            checkModificarEquido.setEnabled(false);
            bBorrarProducto.setEnabled(false);
        }
        if(this.codigoComunidadAutonoma.equals(ConstantesComunes.CODIGO_UBICACION_ANDALUCIA.getString()))
            this.setTitle("ENVIO POR UELN - ANDALUCÍA");
        else if(this.codigoComunidadAutonoma.equals(ConstantesComunes.CODIGO_UBICACION_CASTILLAYLEON.getString()))
            this.setTitle("ENVIO POR UELN - CASTILLA Y LEÓN");
        else if(this.codigoComunidadAutonoma.equals(ConstantesComunes.CODIGO_UBICACION_EXTREMADURA.getString()))
            this.setTitle("ENVIO POR UELN - EXTREMADURA");
        else if(this.codigoComunidadAutonoma.equals(ConstantesComunes.CODIGO_UBICACION_CASTILLA_LA_MANCHA.getString()))
            this.setTitle("ENVIO POR UELN - CASTILLA LA MANCHA");
        else if(this.codigoComunidadAutonoma.equals(ConstantesComunes.CODIGO_UBICACION_MADRID.getString()))
            this.setTitle("ENVIO POR UELN - MADRID");
        else if(this.codigoComunidadAutonoma.equals(ConstantesComunes.CODIGO_UBICACION_GALICIA.getString()))
            this.setTitle("ENVIO POR UELN - GALICIA");
        else if(this.codigoComunidadAutonoma.equals(ConstantesComunes.CODIGO_UBICACION_BALEARES.getString()))
            this.setTitle("ENVIO POR UELN - BALEARES");
        else if(this.codigoComunidadAutonoma.equals(ConstantesComunes.TITULO_VENTANA_BALEARES_ACTUALIZAR_EQUIDO.getString()))
            this.setTitle(ConstantesComunes.TITULO_VENTANA_BALEARES_ACTUALIZAR_EQUIDO.getString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lUELN = new javax.swing.JLabel();
        cUELN = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tDatos = new javax.swing.JTable();
        bEnviar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        cResultado = new javax.swing.JTextArea();
        bLimpiar = new javax.swing.JButton();
        checkCambioTitularidad = new javax.swing.JRadioButton();
        bBorrarProducto = new javax.swing.JButton();
        checkModificarEquido = new javax.swing.JRadioButton();

        setClosable(true);
        setForeground(java.awt.Color.black);
        setMaximizable(true);
        setResizable(true);
        setTitle("Envio de datos por UELN");

        lUELN.setText("UELN:");
        lUELN.setName("lUELN"); // NOI18N

        cUELN.setBackground(new java.awt.Color(255, 255, 153));
        cUELN.setName("cUELN"); // NOI18N
        cUELN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cUELNKeyPressed(evt);
            }
        });

        tDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Campo", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tDatos.setName("tDatos"); // NOI18N
        jScrollPane1.setViewportView(tDatos);

        bEnviar.setText("Enviar");
        bEnviar.setName("bEnviar"); // NOI18N
        bEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnviarActionPerformed(evt);
            }
        });

        cResultado.setEditable(false);
        cResultado.setBackground(new java.awt.Color(255, 255, 204));
        cResultado.setColumns(20);
        cResultado.setRows(5);
        cResultado.setName("cResultado"); // NOI18N
        jScrollPane2.setViewportView(cResultado);

        bLimpiar.setText("Limpiar");
        bLimpiar.setName("bLimpiar"); // NOI18N
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });

        checkCambioTitularidad.setText("Enviar Cambio Titularidad");

        bBorrarProducto.setText("Borrar Producto en CCAA");
        bBorrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarProductoEnCCAA(evt);
            }
        });

        checkModificarEquido.setText("Modificar equido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(lUELN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cUELN, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bEnviar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bBorrarProducto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bLimpiar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(checkCambioTitularidad)
                                        .addGap(41, 41, 41)
                                        .addComponent(checkModificarEquido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lUELN)
                    .addComponent(cUELN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkCambioTitularidad)
                    .addComponent(checkModificarEquido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEnviar)
                    .addComponent(bLimpiar)
                    .addComponent(bBorrarProducto))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cUELNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cUELNKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            int numeroFilas = ((DefaultTableModel)tDatos.getModel()).getRowCount();
            if(numeroFilas>0){
                MostrarMensajes.mensajeInformativo("Por favor, pulse \"Limpiar\" antes de realizar una nueva consulta.");
                return;
            }
            try {
                DefaultTableModel model = ControladorBase.obtenerControlador().obtenerModeloTablaDatosEquidoComAut(cUELN.getText().trim());
                tDatos.setModel(model);
                if(model==null || model.getRowCount()==0){
                    MostrarMensajes.mensajeInformativo("Sin datos para el UELN indicado");
                }
            } catch (Exception e) {
                MostrarMensajes.mensajeExcepcion(e);
            }
        }
    }//GEN-LAST:event_cUELNKeyPressed

    private void bEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnviarActionPerformed
        try {
            if(this.codigoComunidadAutonoma.equals(ConstantesComunes.CODIGO_UBICACION_CASTILLAYLEON.getString()) && this.checkCambioTitularidad.isSelected())
                cResultado.setText(ControladorBase.obtenerControlador().respuestaWSCyLCambioTitularidadDesdeTabla(tDatos));
            else if(this.codigoComunidadAutonoma.equals(ConstantesComunes.CODIGO_UBICACION_EXTREMADURA.getString())){
                if(this.checkCambioTitularidad.isSelected() && this.checkModificarEquido.isSelected())
                    MostrarMensajes.mensajeInformativo("Por favor, seleccionar solo una opción o ninguna. No se pueden procesar las dos opciones");
                else if(this.checkCambioTitularidad.isSelected())    
                    cResultado.setText(ControladorBase.obtenerControlador().respuestaWSJuntaExtremaduraCambioTitularidad(tDatos));
                else if(this.checkModificarEquido.isSelected())
                    cResultado.setText(ControladorBase.obtenerControlador().respuestaWSJuntaExtremaduraModificacion(tDatos));
                else
                    cResultado.setText(ControladorBase.obtenerControlador().respuestaWSViewEnvioPorUELN(codigoComunidadAutonoma, tDatos));
            }
            cResultado.setText(ControladorBase.obtenerControlador().respuestaWSViewEnvioPorUELN(codigoComunidadAutonoma, tDatos));
        } catch (Exception e) {
            MostrarMensajes.mensajeExcepcion(e);
 
        }
    }//GEN-LAST:event_bEnviarActionPerformed

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed
        tDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Campo", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        cUELN.setText("");
        cResultado.setText("");
    }//GEN-LAST:event_bLimpiarActionPerformed

    private void borrarProductoEnCCAA(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarProductoEnCCAA
        try {
            cResultado.setText(ControladorBase.obtenerControlador().respuestaWSCyLBorradoAnimal(tDatos));
        } catch (Exception e) {
            MostrarMensajes.mensajeExcepcion(e);
        }
    }//GEN-LAST:event_borrarProductoEnCCAA


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBorrarProducto;
    private javax.swing.JButton bEnviar;
    private javax.swing.JButton bLimpiar;
    private javax.swing.JTextArea cResultado;
    private javax.swing.JTextField cUELN;
    private javax.swing.JRadioButton checkCambioTitularidad;
    private javax.swing.JRadioButton checkModificarEquido;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lUELN;
    private javax.swing.JTable tDatos;
    // End of variables declaration//GEN-END:variables
}
